### ISSUE TITLE
It appears you didnt do anything different with ToonImport.pyc....

### ISSUE THREAD

**Issue by itsinfinity** [rynogg/rttim#3]
# Embedded file name: toontown\toon\ToonImport.py
from panda3d.core import Multifile
mf = Multifile()
mf.openRead('../resources/phase_14.mf')
mf.setEncryptionFlag(True)
mf.setEncryptionPassword('LegoMyEgo429')
from panda3d.core import VirtualFileSystem

def loadResource():
    vfs = VirtualFileSystem.getGlobalPtr()
    if vfs.mount(mf, '../resources', VirtualFileSystem.MFReadOnly):
        print 'Loaded resources.'

**Comment by toonjoey** [comment]
Nice code. 👍

**Comment by itsinfinity** [comment]
@rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg @rynogg

**Comment by itsinfinity** [comment]
Cracked 3 times in a row w/same password. Damn, how stupid can you get?

**Comment by toonjoey** [comment]
My code is better and the project I worked on had localizer changes and a DNA change.

A Toon DNA change.

Just stop.

**Comment by Nickdoge** [comment]
@itsinfinity fuck off with your bad skippsdev code store

**Comment by itsinfinity** [comment]
Its been completely rewrote, with cogs, trolley, and more. Cant even say it Skipps's now.

**Comment by Sparkpin** [comment]
> toontown\toon\ToonImport.py

yeah seems legit!!!!

**Comment by Nickdoge** [comment]
AHAHAH NIGGA IT CANT EVEN PROPLELY HANDLE INTERESTS @itsinfinity

**Comment by itsinfinity** [comment]
Go away with your TTR code Toontown Standard.

**Comment by MrCheeze446** [comment]
man its funny how you call ryno a skid but he is a dev for TTOFF now and how you call him stupid pretty good man

**Comment by Nickdoge** [comment]
nibba standard is dead @itsinfinity but it wasn't ttr, just saying lol

**Comment by Nickdoge** [comment]
smh infinity went SILENT

**Comment by rynogg** [comment]
i dont really care tbh
im just too lazy to actually change the code

**Comment by itsinfinity** [comment]
Unlike you all, i got stuff to be doing.

**Comment by rynogg** [comment]
i have stuff to do as well
i got some english and history homework to do

**Comment by toonjoey** [comment]
That's an obvious design flaw on your end though. At **least** add some sort of extra encryption somewhere more than an easily decompiled PYC. @rynogg It could be Denuvo for all I care.

**Comment by itsinfinity** [comment]
And I apologize for hating on RTTIM, I would love to see what new features are gonna be added now.

**Comment by Sparkpin** [comment]
@itsinfinity
> Unlike you all, i got stuff to be doing.

Really? So did I! It wasn't anything special, just a date. You?

**Comment by MrCheeze446** [comment]
man i just got done looking over some Shakespeare mono-log im preforming what about you

**Comment by Nickdoge** [comment]
nice

**Comment by Nickdoge** [comment]
yeah sparkpin is gonna get laid i bet infinitydev wont even talk to anyone

**Comment by itsinfinity** [comment]
Im getting laid right now. 🖕

**Comment by itsinfinity** [comment]
@Sparkpin  A date in your dreams doesnt count.

**Comment by MrCheeze446** [comment]
i didnt know that real life was a dream

**Comment by MrCheeze446** [comment]
i also didnt know jacking your self off to skipsOTP was getting laid

**Comment by itsinfinity** [comment]
Atleast i have a 2003 OTP. 😉

**Comment by itsinfinity** [comment]
I didnt know getting ratted by team trap was a thing lol

**Comment by rynogg** [comment]
@itsinfinity it's called stupid mistakes

**Comment by itsinfinity** [comment]
@MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446

**Comment by itsinfinity** [comment]
@MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446

**Comment by itsinfinity** [comment]
@MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 @MrCheeze446 vv
