### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by itsinfinity** [rynogg/rttim#6]
Problem: RTTIM is TTI-based.

Crash details: nigger.exe has stopped working

Log file:
N/A

Questions: 

Why is RTTIM TTI-Based.

**Comment by itsinfinity** [comment]
@rynogg @rynogg   @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg

**Comment by itsinfinity** [comment]
@rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg  @rynogg

**Comment by dotthefox** [comment]
Really infinity? make an actual issue for in development 69.6 not a false issue smh

**Comment by rynogg** [comment]
RTTIM is TTI based because that is what TTMME was based on when I started development on it.  RTTIM literally only started out to show off my naked Toon models.  It should not matter.
RTTIM being TTI based is not an issue.  The only issue is the fact that you still care about RTTIM.
